### ISSUE TITLE
班別の予算残高のレイアウト

### ISSUE THREAD

**Issue by reud** [reud/KBIS_LINEBOT#3]
全角スペースで見やすくする件について提案です。
現行では

設計班:
翼班:
コックピット班:

のようになっていますが、コロンの位置を揃えたら見やすいと思うので、

＿設計班:
＿＿翼班:
コクピ班:

のように先頭に全角スペースを挿入して調整することは可能でしょうか？
(前にもトライしたような気がするけど結果を忘れた)

コックピット班だけ慣習的に「コクピ班」と呼ばれているので省略して差し支えないです。

よろしくお願いします

**Comment by reud** [comment]
余力が出てきたので所属毎に分けても良いです。

**Comment by Toramin10** [comment]
最初からそれだったら別だけど一回一覧でリリースしたからなあ
使いづらくなったって思われるかなあ

**Comment by reud** [comment]
うい
