### ISSUE TITLE
運用方法の解説について

### ISSUE THREAD

**Issue by reud** [reud/KBIS_LINEBOT#4]
一応適当に書いてみたのですが、やり方を知ってしまった今、知らない人向けに書くにはどこまで詳しく書けば良いか分からない状態なので、何か足りない情報や要らない情報があった場合は気軽にコメントを下さい。
誰でも扱えるような状態になったらこのissueはcloseさせて頂きます

**Comment by Toramin10** [comment]
近所のおばあちゃんでも管理できるようになればいいとおもいます。

**Comment by reud** [comment]
近所のおばあちゃんこのサイトに辿り着けないと思います

**Comment by Toramin10** [comment]
Read meを真面目に読んだんですがさっぱり何をすればいいか、何をすればKBISの管理が引き継げるのかわかりませんでした…。

**Comment by reud** [comment]
https://github.com/reud/KBIS_LINEBOT/blob/master/setup.md
書き直しました

**Comment by reud** [comment]
https://github.com/reud/KBIS_LINEBOT/blob/master/%E3%83%87%E3%83%BC%E3%82%BF%E3%81%AE%E5%BC%95%E3%81%8D%E7%B6%99%E3%81%8E%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6.md
具体的に何を引き継ぐのかはこちら

**Comment by Toramin10** [comment]
わかりやすいです！ありがとうございます！

**Comment by reud** [comment]
とりあえず閉めるのでまた疑問点あったら言ってくださいー！
プルリクエストで修正文送ってくれるとめっちゃ楽だしGitHubしてる気がして楽しいのでもし良かったらお願いしますー！
